### ISSUE TITLE
Include data source in CSV file

### ISSUE THREAD

**Issue by anthonyharrison** [jgamblin/patchthisapp#2]
It would be useful if the CSV file identified the sources of the CVEs e.g. KEV, Metapoloit etc

**Comment by jgamblin** [comment]
This is a good enhancement but I will need to rewrite the code that merges the different lists so it may take a little while to be completed.

**Comment by jgamblin** [comment]
@anthonyharrison I was able to get the source added to the CSV file.  Thanks for the suggestion and please let me know if you have any other questions or requests.
